PlatformPublicKey: ""
PlatformSeed: ""
PlatformEmail: ""
PlatformEmailPass: ""
StablecoinCode: ""
StablecoinPublicKey: ""
AnchorUSDCode: ""
AnchorUSDAddress: ""
AnchorUSDTrustLimit: ""
AnchorAPI: ""
Mainnet: ""
