username: supasto@test.com
password: password
seedpwd: x
apiurl: "https://api.openx.solar"
platformPublicKey: "GDHZLFBNYI3C3IHTTDEI6OPU2WDQD2KGD5QOSQJOBXKLSGLNYHQTFXKI"
mapskey: "AIzaSyBi4drFj60P4QHkmxfCxuy8p4_wnDXmCBw"
projIndex: 4
assetName: OXA6fd8ca6bc
sclientid: "c0fe38566a254a3a80b2a42081b46843"
sclientsecret: "46d10252a4954007af5e2f8941aeeb37"
susername: "pr-collab%40swytch.io"
spassword: "S%4091380ee5cfad455a919db9985f913f69"
