username: martin
password: p
seedpwd: x
apiurl: "http://localhost:8081" # opensolar URL
platformPublicKey: "GBSB7CBVVYK3J3DW4Q7E7ODUJQH5GYKNNMKFAN5KBGT7CKZGT2CWMUBL"
mapskey: "AIzaSyBi4drFj60P4QHkmxfCxuy8p4_wnDXmCBw"
projIndex: 1
assetName: TESTTELLER
sclientid: "c0fe38566a254a3a80b2a42081b46843"
sclientsecret: "46d10252a4954007af5e2f8941aeeb37"
susername: "pr-collab%40swytch.io"
spassword: "S%4091380ee5cfad455a919db9985f913f69"
